### PR TITLE
Rework native functions

### LINKED ISSUE #3: Suggestion: Macro to generate NativeFn impls for functions of N arguments
It should be possible to do with a macro_rules macro, generalizing what `Binary` is doing.

### LINKED ISSUE #11: Support for bool args / return values of native functions
[`If`](https://docs.rs/arithmetic-eval/0.1.0/arithmetic_eval/fns/struct.If.html) accepts a `bool` arg, and I want to define a function like 
```rust
.insert_native_fn("in_range", wrap(|a: f32, b: f32, x: f32| -> bool { (a ..= b).contains(&x) }))
```
to use it together with `If`
but it's not possible:
```
error:  the trait bound `arithmetic_eval::fns::wrapper::FnWrapper<_, [closure@41: 455:78]>: arithmetic_eval::values::NativeFn<'_, _>` is not satisfied
error:  the trait `arithmetic_eval::values::NativeFn<'_, _>` is not implemented for `arithmetic_eval::fns::wrapper::FnWrapper<_, [closure@41: 455:78]>`
help:  the following implementations were found:
  <arithmetic_eval::fns::wrapper::FnWrapper<(Ret, T), F> as arithmetic_eval::values::NativeFn<'a, G>>
  <arithmetic_eval::fns::wrapper::FnWrapper<(Ret, T, U), F> as arithmetic_eval::values::NativeFn<'a, G>>
  <arithmetic_eval::fns::wrapper::FnWrapper<(Ret, T, U, V), F> as arithmetic_eval::values::NativeFn<'a, G>>
  <arithmetic_eval::fns::wrapper::FnWrapper<(Ret, T, U, V, W), F> as arithmetic_eval::values::NativeFn<'a, G>>
```

I guess the relevant code is
```rust
macro_rules! arity_fn {
    ($arity:tt => $($arg_name:ident : $t:ident),+) => {
        impl<'a, G, F, Ret, $($t,)+> NativeFn<'a, G> for FnWrapper<(Ret, $($t,)+), F>
        where
            G: Grammar,
            F: Fn($($t,)+) -> Ret,
            $($t: TryFromValue<'a, G>,)+
            Ret: IntoEvalResult<'a, G>,
        {
```

### PR DESCRIPTION
**Pull request by slowli**
...to make their usage easier for a wider range of use cases.

Now, it is possible to define native functions with primitive / tuple / vector arguments and primitive / tuple / vector / result return types.

TODO list:

- [x] Sane error reporting for argument conversion failures and the corresponding tests.

Closes #3, #11.

### CODE REVIEW

**Comment by Boscop** [comment]
This compiles:
```rust
const MIN: fns::Binary<f32> =
	fns::Binary::new(|x, y| if x < y { x } else { y });
const MAX: fns::Binary<fn(f32, f32) -> f32> =
	fns::Binary::new(|x, y| if x > y { x } else { y });
```
But shouldn't `MAX` give a compile error (because it should now be `fns::Binary<f32>`)?

**Comment by Boscop** [comment]
I encountered another issue related to this: https://github.com/slowli/arithmetic-parser/issues/11

**Comment by slowli** [comment]
> But shouldn't `MAX` give a compile error

Nope, turns out that `fn` pointers are comparable (this was news for me as well 🙃). For example, this code compiles / runs:

```rust
fn main() {
    let foo: fn(f32) -> f32 = f32::abs;
    let bar: fn(f32) -> f32 = f32::signum;
    println!("{}", foo < bar);
}
```

**Comment by slowli** [comment]
I'm merging this to streamline working on other issues. Further improvements if any will be addressed in separate PRs.

**Pull request merged**
